spring.application.name=gridweaver
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gridweaver?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cors.allowed-origins=http://localhost:5173

# Enable Java 21 Virtual Threads (Project Loom)
spring.threads.virtual.enabled=true

